# Generated by Django 5.2.7 on 2025-10-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cash_balaUsernce',
            new_name='cash_balance',
        ),
    ]
