# Generated by Django 5.2.7 on 2025-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_rename_cash_balausernce_userprofile_cash_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
