# Generated by Django 5.2.7 on 2025-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID from API')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Last Traded Price', max_digits=15)),
                ('quantity', models.IntegerField(help_text='Quantity')),
                ('percentage_change', models.DecimalField(decimal_places=5, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=20)),
                ('share_volume', models.IntegerField()),
                ('trade_volume', models.IntegerField()),
                ('crossing_volume', models.IntegerField()),
                ('crossing_trade_vol', models.IntegerField()),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=25)),
                ('market_cap_percentage', models.DecimalField(decimal_places=5, max_digits=10)),
                ('status', models.IntegerField(help_text='Status code from API')),
                ('last_traded_time', models.BigIntegerField(help_text='Last Traded Time (milliseconds since epoch)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
                'ordering': ['symbol'],
            },
        ),
    ]
